import type { StoreData } from "@/store/usePensionStore";

export interface PersonaMetrics {
  monthlyPensionTarget: string;    // 은퇴 후 가구 월 목표 수령액
  totalAccumulatedAssets: string;  // 총 연금 및 투자 적립 자산
  structureType: string;           // 연금 포트폴리오 구조
  strategyTip: string;             // 핵심 설계 및 절세 포인트
}

export interface PersonaPreset {
  id: string;
  title: string;
  subtitle: string;
  tag: string;
  tagColor: string;
  icon: string;
  targetUserDesc: string;
  keyFeatures: string[];
  summaryMetrics: PersonaMetrics;
  data: Partial<StoreData>;
}

export const PERSONA_PRESETS: PersonaPreset[] = [
  {
    id: "COUPLE_WORKPLACE",
    title: "40대 평균 맞벌이 직장인 부부",
    subtitle: "안정형 3층 연금 · 자녀 양육 및 표준 은퇴 준비",
    tag: "표준 맞벌이",
    tagColor: "#6366f1",
    icon: "💼",
    targetUserDesc: "부부 모두 국민연금 및 퇴직연금(DC)을 성실히 적립 중인 대한민국 대표 40대 중산층 가구",
    keyFeatures: [
      "부부 합산 국민연금 예상 수령액 월 205만원 (본인 120만 + 배우자 85만)",
      "부부 DC형 퇴직연금 1억 3,500만원 + 연금저축 7,000만원 성실 적립",
      "S4 전략: 5,000만원 커버드콜 배당 복리 재투자(스노우볼)로 은퇴 시점 자산 증대",
      "60대 350만 / 70대 300만 / 80대 250만원의 현실적 생애주기 지출 곡선",
    ],
    summaryMetrics: {
      monthlyPensionTarget: "월 330만 ~ 350만원",
      totalAccumulatedAssets: "사적연금 약 2.05억원 + 월배당 5,000만원",
      structureType: "균형 잡힌 표준 3층 연금형",
      strategyTip: "스노우볼 복리 재투자로 은퇴 시점 사적연금 볼륨 극대화",
    },
    data: {
      nationalPension: {
        contributionMonths: 240,
        totalPaidAmount: 7560,
        currentStandardMonthlyIncome: 420,
        expectedTotalContributionMonths: 360,
        expectedMonthlyPension: 120,
        totalExpectedPremium: 11340,
        basicPensionAmount: 120,
        aValue: 298,
        bValue: 420,
      },
      basicPension: {
        householdType: "COUPLE",
        recognizedIncome: 0,
        expectedEligibility: false,
        expectedMonthlyAmount: 0,
        region: "METRO",
        generalProperty: 35000,
        financialAssets: 5000,
        debts: 10000,
        luxuryAssets: 0,
        selfEarnedIncome: 0,
        selfOtherIncome: 0,
        selfOccupational: false,
        spouseEarnedIncome: 0,
        spouseOtherIncome: 0,
        spouseOccupational: false,
        applyToSimulation: false,
      },
      retirementPensions: [
        {
          id: "ret-self-dc-1",
          pensionType: "DC",
          totalAccumulated: 8500,
          monthlyContribution: 35,
          companyMatchRate: 0,
          expectedReturnRate: 3.5,
          provider: "한국투자증권",
          productName: "한국투자 TDF 2040 채권혼합",
        },
      ],
      personalPensions: [
        {
          id: "pers-self-fund-1",
          savingsType: "FUND",
          totalAccumulated: 4200,
          monthlyAnnualContribution: 34,
          desiredStartAge: 65,
          receivingPeriod: 20,
          provider: "삼성증권",
          productName: "S&P500 인덱스 연금저축펀드",
        },
      ],
      pensionInsurances: [],
      additionalPayment: {
        firstEnrollYm: "",
        resumeYm: "",
        gapMonths: 0,
        gapReason: "EXEMPT",
        enrollStatus: "WORKPLACE",
        receivedLumpSumRefund: false,
        requestedMonths: 0,
        baseIncome: 100,
        paymentMode: "LUMP",
        installments: 12,
        installmentInterestRate: 2.5,
        applyYm: "",
        marginalTaxRate: 16.5,
        applyToSimulation: false,
      },
      returnRepayment: {
        refundAmount: 0,
        refundYm: "",
        restoredMonths: 0,
        periodStartYm: "",
        noticeAmount: 0,
        applyYm: "",
        installments: 1,
        applyToSimulation: false,
      },
      spouse: {
        nationalPension: {
          contributionMonths: 180,
          totalPaidAmount: 4185,
          currentStandardMonthlyIncome: 310,
          expectedTotalContributionMonths: 300,
          expectedMonthlyPension: 85,
          totalExpectedPremium: 6975,
          basicPensionAmount: 85,
          aValue: 298,
          bValue: 310,
        },
        additionalPayment: {
          firstEnrollYm: "",
          resumeYm: "",
          gapMonths: 0,
          gapReason: "EXEMPT",
          enrollStatus: "WORKPLACE",
          receivedLumpSumRefund: false,
          requestedMonths: 0,
          baseIncome: 100,
          paymentMode: "LUMP",
          installments: 12,
          installmentInterestRate: 2.5,
          applyYm: "",
          marginalTaxRate: 16.5,
          applyToSimulation: false,
        },
        returnRepayment: {
          refundAmount: 0,
          refundYm: "",
          restoredMonths: 0,
          periodStartYm: "",
          noticeAmount: 0,
          applyYm: "",
          installments: 1,
          applyToSimulation: false,
        },
        retirementPensions: [
          {
            id: "ret-spouse-dc-1",
            pensionType: "DC",
            totalAccumulated: 5000,
            monthlyContribution: 25,
            companyMatchRate: 0,
            expectedReturnRate: 3.0,
            provider: "미래에셋증권",
            productName: "미래에셋 글로벌인덱스 40",
          },
        ],
        personalPensions: [
          {
            id: "pers-spouse-fund-1",
            savingsType: "FUND",
            totalAccumulated: 2800,
            monthlyAnnualContribution: 25,
            desiredStartAge: 65,
            receivingPeriod: 20,
            provider: "신한투자증권",
            productName: "한국배당다우존스 연금저축",
          },
        ],
        pensionInsurances: [],
      },
      simulationParams: {
        currentAge: 48,
        retirementAge: 60,
        expectedLifeExpectancy: 85,
        inflationRate: 3.0,
        nationalPensionStartAge: 65,
        hasSpouse: true,
        spouseAge: 46,
        birthYear: 1978,
        spouseBirthYear: 1980,
        childrenCount: 2,
        childrenAges: "16, 13",
        targetMonthlySpending: 350,
        minMonthlySpending: 230,
        childSupportExpense: 80,
        annualMedicalExpense: 150,
        nonPensionAssets: 12000,
        propertyTaxBase: 35000,
        financialIncome: 300,
        decumulationStrategy: "DECREASING",
        spendingPattern: "AGE_BANDS",
        activePhaseYears: 5,
        annualDeclineRate: 2.0,
        ageBands: {
          age60s: { target: 350, min: 230 },
          age70s: { target: 300, min: 200 },
          age80s: { target: 250, min: 170 },
          age90s: { target: 220, min: 150 },
        },
        coveredCallAsset: 5000,
        coveredCallDividendRate: 9.0,
        isCoupleDivided: true,
        dividendPolicy: "REINVEST",
        spouseRetirementAge: 60,
        spouseLifeExpectancy: 88,
        spouseNationalPensionStartAge: 65,
        nationalPensionDeferYears: 0,
        spouseNationalPensionDeferYears: 0,
        privateDrawStartAge: 0,
        privatePensionEndAge: 0,
        spousePrivatePensionEndAge: 0,
      },
    },
  },
  {
    id: "SINGLE_EARNER_CORP",
    title: "50대 외벌이 대기업·공기업 퇴직 준비 부부",
    subtitle: "고액 퇴직금 절세 설계 · 국민연금 추납 및 IRP 분할 인출",
    tag: "퇴직 임박 집중형",
    tagColor: "#059669",
    icon: "🏢",
    targetUserDesc: "은퇴를 5년 앞두고 일시금 퇴직금과 IRP 장기 절세 인출 및 국민연금 추납 전략이 필요한 가구",
    keyFeatures: [
      "본인 국민연금 320개월 납부 (월 185만원) + 추납 24개월 시뮬레이션 즉시 반영",
      "배우자 전업주부 임의가입 120개월 달성 (월 42만원, 부부 합산 227만원)",
      "DB형 퇴직금 2.8억원 + IRP 1.2억원 + 개인연금저축/보험 1.45억원 메가 자산",
      "S4 전략: 1억 2,000만원 커버드콜 배당 비상자금 안전버퍼(BUFFER) 적립 운용",
    ],
    summaryMetrics: {
      monthlyPensionTarget: "월 400만 ~ 450만원",
      totalAccumulatedAssets: "퇴직금·사적연금 약 5.45억원 + 월배당 1.2억원",
      structureType: "공적연금 고액 + 2층 퇴직연금 메가볼륨",
      strategyTip: "퇴직소득세 이연(30~40% 절세) 및 10년 이상 장기 분할 수령",
    },
    data: {
      nationalPension: {
        contributionMonths: 320,
        totalPaidAmount: 12800,
        currentStandardMonthlyIncome: 590,
        expectedTotalContributionMonths: 380,
        expectedMonthlyPension: 185,
        totalExpectedPremium: 15200,
        basicPensionAmount: 185,
        aValue: 298,
        bValue: 590,
      },
      basicPension: {
        householdType: "COUPLE",
        recognizedIncome: 0,
        expectedEligibility: false,
        expectedMonthlyAmount: 0,
        region: "METRO",
        generalProperty: 65000,
        financialAssets: 15000,
        debts: 5000,
        luxuryAssets: 0,
        selfEarnedIncome: 0,
        selfOtherIncome: 0,
        selfOccupational: false,
        spouseEarnedIncome: 0,
        spouseOtherIncome: 0,
        spouseOccupational: false,
        applyToSimulation: false,
      },
      retirementPensions: [
        {
          id: "ret-self-db-1",
          pensionType: "DB",
          avgSalary: 750,
          yearsOfService: 28,
          salaryGrowthRate: 3.0,
          expectedLumpSum: 28000,
          provider: "IBK기업은행",
          productName: "대기업 확정급여형(DB) 퇴직연금",
        },
        {
          id: "ret-self-irp-1",
          pensionType: "IRP",
          totalAccumulated: 12000,
          monthlyContribution: 50,
          expectedReturnRate: 4.0,
          provider: "미래에셋증권",
          productName: "개인형 IRP 채권혼합 안심플랜",
        },
      ],
      personalPensions: [
        {
          id: "pers-self-fund-2",
          savingsType: "FUND",
          totalAccumulated: 9000,
          monthlyAnnualContribution: 50,
          desiredStartAge: 60,
          receivingPeriod: 20,
          provider: "KB증권",
          productName: "연금저축 글로벌배당성장 펀드",
        },
      ],
      pensionInsurances: [
        {
          id: "ins-self-1",
          insuranceType: "일반연금보험",
          totalAccumulated: 3000,
          monthlyPayment: 0,
          paymentPeriod: 10,
          expectedDeclaredRate: 2.8,
          provider: "한화생명",
          productName: "스마트플러스 연금보험 (완납)",
        },
      ],
      additionalPayment: {
        firstEnrollYm: "1997-03",
        resumeYm: "2001-04",
        gapMonths: 24,
        gapReason: "EXEMPT",
        enrollStatus: "WORKPLACE",
        receivedLumpSumRefund: false,
        requestedMonths: 24,
        baseIncome: 300,
        paymentMode: "LUMP",
        installments: 1,
        installmentInterestRate: 2.5,
        applyYm: "2026-05",
        marginalTaxRate: 26.4,
        applyToSimulation: true,
      },
      returnRepayment: {
        refundAmount: 0,
        refundYm: "",
        restoredMonths: 0,
        periodStartYm: "",
        noticeAmount: 0,
        applyYm: "",
        installments: 1,
        applyToSimulation: false,
      },
      spouse: {
        nationalPension: {
          contributionMonths: 120,
          totalPaidAmount: 1080,
          currentStandardMonthlyIncome: 100,
          expectedTotalContributionMonths: 120,
          expectedMonthlyPension: 42,
          totalExpectedPremium: 1080,
          basicPensionAmount: 42,
          aValue: 298,
          bValue: 100,
        },
        additionalPayment: {
          firstEnrollYm: "",
          resumeYm: "",
          gapMonths: 0,
          gapReason: "EXEMPT",
          enrollStatus: "VOLUNTARY",
          receivedLumpSumRefund: false,
          requestedMonths: 0,
          baseIncome: 100,
          paymentMode: "LUMP",
          installments: 12,
          installmentInterestRate: 2.5,
          applyYm: "",
          marginalTaxRate: 16.5,
          applyToSimulation: false,
        },
        returnRepayment: {
          refundAmount: 0,
          refundYm: "",
          restoredMonths: 0,
          periodStartYm: "",
          noticeAmount: 0,
          applyYm: "",
          installments: 1,
          applyToSimulation: false,
        },
        retirementPensions: [],
        personalPensions: [
          {
            id: "pers-spouse-ins-1",
            savingsType: "INSURANCE",
            totalAccumulated: 2500,
            monthlyAnnualContribution: 0,
            desiredStartAge: 65,
            receivingPeriod: 20,
            provider: "삼성생명",
            productName: "무배당 연금저축보험 (완납)",
          },
        ],
        pensionInsurances: [],
      },
      simulationParams: {
        currentAge: 55,
        retirementAge: 60,
        expectedLifeExpectancy: 85,
        inflationRate: 2.8,
        nationalPensionStartAge: 63,
        hasSpouse: true,
        spouseAge: 53,
        birthYear: 1971,
        spouseBirthYear: 1973,
        childrenCount: 1,
        childrenAges: "22",
        targetMonthlySpending: 450,
        minMonthlySpending: 280,
        childSupportExpense: 50,
        annualMedicalExpense: 200,
        nonPensionAssets: 35000,
        propertyTaxBase: 55000,
        financialIncome: 800,
        decumulationStrategy: "DECREASING",
        spendingPattern: "AGE_BANDS",
        activePhaseYears: 5,
        annualDeclineRate: 2.2,
        ageBands: {
          age60s: { target: 450, min: 280 },
          age70s: { target: 380, min: 240 },
          age80s: { target: 300, min: 200 },
          age90s: { target: 250, min: 180 },
        },
        coveredCallAsset: 12000,
        coveredCallDividendRate: 9.0,
        isCoupleDivided: true,
        dividendPolicy: "BUFFER",
        spouseRetirementAge: 60,
        spouseLifeExpectancy: 88,
        spouseNationalPensionStartAge: 64,
        nationalPensionDeferYears: 0,
        spouseNationalPensionDeferYears: 0,
        privateDrawStartAge: 60,
        privatePensionEndAge: 80,
        spousePrivatePensionEndAge: 85,
      },
    },
  },
  {
    id: "SELF_EMPLOYED",
    title: "40대 자영업·전문직 프리랜서 실속 부부",
    subtitle: "퇴직금 공백 극복 · IRP & 고배당 월지급 파이프라인 집중",
    tag: "배당·현금흐름 집중형",
    tagColor: "#d97706",
    icon: "☕",
    targetUserDesc: "퇴직금이 없는 자영업·프리랜서로서 IRP, 노란우산공제, 월배당 ETF로 자체 은퇴 현금흐름을 구축하려는 가구",
    keyFeatures: [
      "부부 국민연금 지역가입 합산 예상액 월 135만원 (본인 75만 + 배우자 60만)",
      "자영업 IRP 각 3,000만원/1,500만원 + 노란우산 및 연금저축 1억 500만원",
      "S4 전략: 8,000만원 커버드콜 배당 전액소비(PAYOUT)로 공적연금 공백 즉시 보완",
      "65세까지 현역 활동(늦은 은퇴)으로 소득 공백기를 최소화하는 현실적 로드맵",
    ],
    summaryMetrics: {
      monthlyPensionTarget: "월 280만 ~ 300만원",
      totalAccumulatedAssets: "사적연금 약 1.5억원 + 월배당 8,000만원",
      structureType: "사적연금 + 월배당 하이브리드 주도형",
      strategyTip: "연금 개시 전 커버드콜 월배당금으로 생활비 보당 및 공백기 극복",
    },
    data: {
      nationalPension: {
        contributionMonths: 190,
        totalPaidAmount: 4200,
        currentStandardMonthlyIncome: 280,
        expectedTotalContributionMonths: 340,
        expectedMonthlyPension: 75,
        totalExpectedPremium: 7500,
        basicPensionAmount: 75,
        aValue: 298,
        bValue: 280,
      },
      basicPension: {
        householdType: "COUPLE",
        recognizedIncome: 0,
        expectedEligibility: false,
        expectedMonthlyAmount: 0,
        region: "CITY",
        generalProperty: 28000,
        financialAssets: 8000,
        debts: 6000,
        luxuryAssets: 0,
        selfEarnedIncome: 0,
        selfOtherIncome: 0,
        selfOccupational: false,
        spouseEarnedIncome: 0,
        spouseOtherIncome: 0,
        spouseOccupational: false,
        applyToSimulation: false,
      },
      retirementPensions: [
        {
          id: "ret-self-irp-selfemp",
          pensionType: "IRP",
          totalAccumulated: 3000,
          monthlyContribution: 50,
          companyMatchRate: 0,
          expectedReturnRate: 4.5,
          provider: "토스증권",
          productName: "자영업자 개인형 IRP 채권혼합",
        },
      ],
      personalPensions: [
        {
          id: "pers-self-fund-selfemp",
          savingsType: "FUND",
          totalAccumulated: 6500,
          monthlyAnnualContribution: 50,
          desiredStartAge: 65,
          receivingPeriod: 20,
          provider: "미래에셋증권",
          productName: "노란우산공제 & 연금저축 통합플랜",
        },
      ],
      pensionInsurances: [],
      additionalPayment: {
        firstEnrollYm: "",
        resumeYm: "",
        gapMonths: 0,
        gapReason: "EXEMPT",
        enrollStatus: "REGIONAL",
        receivedLumpSumRefund: false,
        requestedMonths: 0,
        baseIncome: 100,
        paymentMode: "LUMP",
        installments: 12,
        installmentInterestRate: 2.5,
        applyYm: "",
        marginalTaxRate: 16.5,
        applyToSimulation: false,
      },
      returnRepayment: {
        refundAmount: 0,
        refundYm: "",
        restoredMonths: 0,
        periodStartYm: "",
        noticeAmount: 0,
        applyYm: "",
        installments: 1,
        applyToSimulation: false,
      },
      spouse: {
        nationalPension: {
          contributionMonths: 140,
          totalPaidAmount: 2600,
          currentStandardMonthlyIncome: 220,
          expectedTotalContributionMonths: 280,
          expectedMonthlyPension: 60,
          totalExpectedPremium: 5200,
          basicPensionAmount: 60,
          aValue: 298,
          bValue: 220,
        },
        additionalPayment: {
          firstEnrollYm: "",
          resumeYm: "",
          gapMonths: 0,
          gapReason: "EXEMPT",
          enrollStatus: "REGIONAL",
          receivedLumpSumRefund: false,
          requestedMonths: 0,
          baseIncome: 100,
          paymentMode: "LUMP",
          installments: 12,
          installmentInterestRate: 2.5,
          applyYm: "",
          marginalTaxRate: 16.5,
          applyToSimulation: false,
        },
        returnRepayment: {
          refundAmount: 0,
          refundYm: "",
          restoredMonths: 0,
          periodStartYm: "",
          noticeAmount: 0,
          applyYm: "",
          installments: 1,
          applyToSimulation: false,
        },
        retirementPensions: [
          {
            id: "ret-spouse-irp-selfemp",
            pensionType: "IRP",
            totalAccumulated: 1500,
            monthlyContribution: 30,
            companyMatchRate: 0,
            expectedReturnRate: 4.0,
            provider: "카카오페이증권",
            productName: "프리랜서 실속 IRP",
          },
        ],
        personalPensions: [
          {
            id: "pers-spouse-fund-selfemp",
            savingsType: "FUND",
            totalAccumulated: 4000,
            monthlyAnnualContribution: 30,
            desiredStartAge: 63,
            receivingPeriod: 20,
            provider: "NH투자증권",
            productName: "연금저축 글로벌성장 펀드",
          },
        ],
        pensionInsurances: [],
      },
      simulationParams: {
        currentAge: 45,
        retirementAge: 65,
        expectedLifeExpectancy: 85,
        inflationRate: 3.0,
        nationalPensionStartAge: 65,
        hasSpouse: true,
        spouseAge: 43,
        birthYear: 1981,
        spouseBirthYear: 1983,
        childrenCount: 2,
        childrenAges: "12, 9",
        targetMonthlySpending: 280,
        minMonthlySpending: 190,
        childSupportExpense: 60,
        annualMedicalExpense: 120,
        nonPensionAssets: 15000,
        propertyTaxBase: 28000,
        financialIncome: 400,
        decumulationStrategy: "DECREASING",
        spendingPattern: "AGE_BANDS",
        activePhaseYears: 5,
        annualDeclineRate: 2.0,
        ageBands: {
          age60s: { target: 280, min: 190 },
          age70s: { target: 240, min: 170 },
          age80s: { target: 200, min: 150 },
          age90s: { target: 180, min: 130 },
        },
        coveredCallAsset: 8000,
        coveredCallDividendRate: 9.5,
        isCoupleDivided: true,
        dividendPolicy: "PAYOUT",
        spouseRetirementAge: 63,
        spouseLifeExpectancy: 88,
        spouseNationalPensionStartAge: 65,
        nationalPensionDeferYears: 0,
        spouseNationalPensionDeferYears: 0,
        privateDrawStartAge: 63,
        privatePensionEndAge: 85,
        spousePrivatePensionEndAge: 88,
      },
    },
  },
];

export function getPersonaById(id: string): PersonaPreset | undefined {
  return PERSONA_PRESETS.find((p) => p.id === id);
}
